mpi_type:
  - external
  - conda
docker_image:  # [linux and x86_64]
  - quay.io/condaforge/linux-anvil-cos7-cuda:10.2     # [linux and x86_64]
cudatoolkit:  # [linux and x86_64]
  - 10.2      # [linux and x86_64]
enable_cuda:
  - True      # [linux and x86_64]
  - False     # [not (linux and x86_64)]
