mpi_type:
  - external
  - conda
docker_image:  # [linux]
  - quay.io/condaforge/linux-anvil-cos7-cuda:10.2     # [linux and x86_64]
  - quay.io/condaforge/linux-anvil-aarch64-cuda:11.2  # [linux and aarch64]
  - quay.io/condaforge/linux-anvil-ppc64le-cuda:10.2  # [linux and ppc64le]
