docker_image:                                # [os.environ.get("BUILD_PLATFORM", "").startswith("linux") or (os.environ.get("CONFIG_VERSION", "1") == "1" and linux)]
   - quay.io/condaforge/linux-anvil-comp7    # [os.environ.get("BUILD_PLATFORM") == "linux-64" or (os.environ.get("CONFIG_VERSION", "1") == "1" and linux64)]
   - quay.io/condaforge/linux-anvil-cuda:9.2        # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
   - quay.io/condaforge/linux-anvil-cuda:10.2       # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]

cuda_compiler:   # [linux64]
  - nvcc         # [linux64]

cuda_compiler_version:
  - None                       # [linux64]
  - 9.2                        # [linux64]
  - 10.2                       # [linux64]

cudnn:
  - undefined                  # [linux64]
  - 7                          # [linux64]
  - 7                          # [linux64]

cdt_name:  # [linux]
  - cos7   # [linux64]
  - cos6   # [linux64]
  - cos6   # [linux64]
