mpi_type:
  - external                                           # [linux]
  - conda
c_compiler_version:                                    # [linux]
  - 9                                                  # [linux]
cxx_compiler_version:                                  # [linux]
  - 9                                                  # [linux]
fortran_compiler_version:                              # [linux]
  - 9                                                  # [linux]
cudnn:                                                 # [linux]
  - 8                                                  # [linux]
cdt_name:                                              # [linux]
  - cos7                                               # [linux]
docker_image:                                          # [linux]
  - quay.io/condaforge/linux-anvil-cos7-cuda:11.0      # [linux64]
  - quay.io/condaforge/linux-anvil-ppc64le-cuda:11.0   # [ppc64le]
  - quay.io/condaforge/linux-anvil-aarch64-cuda:11.0   # [aarch64]
cuda_compiler_version:                                 # [linux]
  - 11.0                                               # [linux]
