mpi_type:
  - external                                           # [linux]
  - conda
c_compiler_version:                                    # [linux]
  - 10                                                 # [linux]
cxx_compiler_version:                                  # [linux]
  - 10                                                 # [linux]
fortran_compiler_version:                              # [linux]
  - 10                                                 # [linux]
cudnn:                                                 # [linux]
  - 8                                                  # [linux]
cdt_name:                                              # [linux]
  - cos7                                               # [linux]
docker_image:                                          # [linux]
  - quay.io/condaforge/linux-anvil-cuda:11.1           # [linux64]
  - quay.io/condaforge/linux-anvil-ppc64le-cuda:11.1   # [ppc64le]
  - quay.io/condaforge/linux-anvil-aarch64-cuda:11.1   # [aarch64]
cuda_compiler:                                         # [linux]
  - nvcc                                               # [linux]
cuda_compiler_version:                                 # [linux]
  - 11.1                                               # [linux]
